name = "containers"
parent = "tedge-rugpi-core/tedge"

recipes = [
    "tedge-rugpi-core/defaults",
    "tedge-rugpi-core/docker",
    "tedge-config",
]

[parameters."core/apt-cleanup"]
autoremove = true

[parameters."core/rugpi-ctrl"]
rugpi_admin = true  # Enable Rugpi Admin.

[parameters."tedge-config"]
# Allow containers to reach the MQTT broker on the host
mqtt_bind_address = "0.0.0.0"
