parent = "tedge-rugpi-core/raspios-tedge"

recipes = [
    "core/rugpi-ctrl",
    "tedge-rugpi-core/docker",
    "tedge-config",
]

[parameters."core/rugpi-ctrl"]
rugpi_admin = true  # Enable Rugpi Admin.

[parameters."tedge-config"]
# Allow containers to reach the MQTT broker on the host
mqtt_bind_address = "0.0.0.0"
