parent = "tedge-rugpi-core/raspios-tedge"

recipes = [
    "core/rugpi-ctrl",
    "tedge-rugpi-core/systemd-resolved",
    "tedge-rugpi-core/boot-options",
]

[parameters."core/rugpi-ctrl"]
rugpi_admin = true
