name: Bake Image

on:
  push:
    branches:
      - main
      - ci

env:
  PI_BASE_IMAGE: "https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-10-10/2023-10-10-raspios-bookworm-arm64-lite.img.xz"

jobs:  
  bake-image:
    name: Bake Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set image name
        run: echo "IMAGE_NAME=tedge_rugpi_$(date +'%Y-%m-%d-%H%M').img" >> $GITHUB_ENV

      - name: Install QEMU
        run: docker run --privileged --rm tonistiigi/binfmt --install arm64

      - name: Extract Image
        run: ./run-bakery extract ${{ env.PI_BASE_IMAGE }} build/base.tar
      
      - name: Customize System
        run: ./run-bakery customize build/base.tar build/customized.tar
      
      - name: Bake Image
        run:
          ./run-bakery bake build/customized.tar build/${{ env.IMAGE_NAME }}

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME }}
          path: build/${{ env.IMAGE_NAME }}
